TechnicalForum/urls.py
from django.conf.urls import url
from django.contrib import admin
from tech import views
from django.conf.urls import url,include
from rest_framework import routers
from tech import classviews
from django.conf.urls.static import static
from django.conf import settings

router=routers.DefaultRouter()
router.register(r'item_set',classviews.TodoitemViewset)
router.register(r'list_set',classviews.TodolistViewset)

urlpatterns = [
    url(r'^tech/',include("tech.urls")),
    url(r'^admin/', admin.site.urls),
    url(r'',include("django.contrib.auth.urls")),
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tech/urls.py
from django.conf.urls import url
from django.contrib import admin
from tech import views
from tech.classviews import LListView,LCreateView,LDetailView,ICreateView,LUpdateView,LDeleteView,CCreateView,UserUpdateView
from django.contrib.auth.views import password_reset
urlpatterns = [
    url(r'^question/',views.questions,name='create'),
    url(r'^question/',views.questions,name='update'),
    url(r'^question/',views.questions,name='delete'),
    url(r'^question/',views.questions,name='create_comment'),
    url(r'^questions/(?P<pk>[0-9]*)/',LDetailView.as_view(template_name='questions_detail.html')),
    url(r'^create/questions/',LCreateView.as_view(template_name='questions_create.html')),
    url(r'^create/comments/(?P<pk>[0-9]*)/',CCreateView.as_view(template_name='comments_create.html'),name='create_comment_1'),
    url(r'^delete/(?P<pk>[0-9]*)/$',LDeleteView.as_view(template_name='questions_confirm_delete.html')),
    url(r'update/questions/(?P<pk>[0-9]*)/',LUpdateView.as_view(template_name='questions_create.html')),
    url(r'^create/answers/(?P<pk>[0-9]*)/',ICreateView.as_view(template_name='answers_create.html'),name='create_answer_1'),
    url(r'^question/',views.questions,name='item'),
    url(r'^answers/(?P<questions>[0-9]*)/',views.answers),
    url(r'^comments/(?P<answers>[0-9]*)/',views.comments),
    url(r'list/$',views.list),
    url(r'list_details/(?P<pk>[0-9]*)/$',views.list_detail),
    url(r'homepage/',views.homepage),
    url(r'register/',views.adduser),
    url(r'profile/',views.profile,name='photo'),
    url(r'update/photo/(?P<pk>[0-9]*)/',UserUpdateView.as_view(template_name='profile_photo.html')),
    url(r'profile1/(?P<user_id_id>[0-9]*)/',views.profile1),
    url(r'edit/details/(?P<pk>[0-9]*)/',views.update_user),
    url(r'leaderboard/',views.leader)
]

tech/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models

class User_points(models.Model):
    user_id=models.ForeignKey(User)
    credits=models.IntegerField()
    photo=models.ImageField(height_field='height',width_field='width',default='/static/sample.png')
    height=models.IntegerField(default=20)
    width=models.IntegerField(default=20)

class Question(models.Model):
    # question_id=models.IntegerField(auto_created=True)
    user = models.ForeignKey(User)
    pic=models.ForeignKey(User_points)
    questions=models.TextField()

    def __unicode__(self):
        return self.questions

class Answer(models.Model):
    user = models.ForeignKey(User)
    pic=models.ForeignKey(User_points)
    question_id=models.ForeignKey(Question)
    answers=models.TextField()
    def __unicode__(self):
        return self.answers

class Comment(models.Model):
    user = models.ForeignKey(User)
    pic=models.ForeignKey(User_points)
    answer_id=models.ForeignKey(Answer)
    comments=models.TextField()

templates/answers.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load staticfiles %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
<link rel="stylesheet" href="/lib/w3-theme-blue.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <style>
        .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }

    /* Add a gray background color and some padding to the footer */
    footer {
      background-color: #f2f2f2;
      padding: 25px;
    }

    </style>

</head>
<body class="bg2">
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/tech/question">TechnicalForum</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">

      <ul class="nav navbar-nav navbar-right">
          <li><a href="/tech/leaderboard"><span class="glyphicon glyphicon-log-in"></span> Leader Board</a></li>
        <li><a href="/tech/profile"><span class="glyphicon glyphicon-log-in"></span> Profile</a></li>
          <li><a href="/logout"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
      </ul>
    </div>
  </div>
</nav>
<div class="w3-card-4">
<div class="w3-panel w3-light-grey w3-border">
    <h1><p><img class="img-rounded" height="50" width="50" src={{ question.pic.photo.url }}/>   {{ question.questions }}</p></h1><br>
</div>
<div class="w3-container w3-theme w3-card-2">

<h2>Answers</h2>
</div>
    <ul class="list-group">
        {% for record1 in item %}
        <li class="w3-theme-l3" style="position:relative"> <a class="list-group-item" href="{% url 'tech.views.comments' record1.id %}"><b><img class="img-rounded" height="20" width="20" src={{ record1.pic.photo.url }}/><font color="#dc143c">{{ record1.user.username }}</font> </b> {{ record1.answers }} </a></li>

        {% endfor %}
    </ul></div>
<br><h4>
<a class="btn btn-primary" href= '{% url 'create_answer_1' question.id %}' role="button">Add new Answer</a>
</h4>
</body>
</html>

templates/answers_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load staticfiles %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <style>
        .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }

    /* Add a gray background color and some padding to the footer */
    footer {
      background-color: #f2f2f2;
      padding: 25px;
    }

    </style>
</head>
<body class="bg2">
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/tech/question">TechnicalForum</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">

      <ul class="nav navbar-nav navbar-right">
          <li><a href="/tech/leaderboard"><span class="glyphicon glyphicon-log-in"></span> Leader Board</a></li>
        <li><a href="/tech/profile"><span class="glyphicon glyphicon-log-in"></span> Profile</a></li>
          <li><a href="/logout"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
      </ul>
    </div>
  </div>
</nav>
<br><br><center>
<form class="form-horizontal" method="post">{% csrf_token %}
    <fieldset>
        <legend>{{ title }}</legend>
        {% for field in form %}<h2>
            {% if field.errors %}
                <div class="control-group error">
                    <label class="control-label">{{ field.label }}</label>
                    <div class="controls">{{ field }}
                        <span class="help-inline">
                            {% for error in  field.errors %}{{ error }}{% endfor %}
                        </span>
                    </div>
                </div>
            {% else %}
                <div class="control-group">
                    <label class="control-label">{{ field.label }}</label>
                    <div class="controls">{{ field }}
                        {% if field.help_text %}
                            <p class="help-inline"><small>{{ field.help_text }}</small></p>
                        {% endif %}
                    </div>
                </div>
            {% endif %}<br></h2>
        {% endfor %}
    </fieldset>
    <div class="form-actions">
        <button type="submit" class="btn btn-primary" >Submit</button>
    </div>
</form>
</center>
</body>
</html>

templates/comments.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load staticfiles %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
<link rel="stylesheet" href="/lib/w3-theme-blue.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <style>
        .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }

    /* Add a gray background color and some padding to the footer */
    footer {
      background-color: #f2f2f2;
      padding: 25px;
    }

    </style>

</head>
<body class="bg2">
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/tech/question">TechnicalForum</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">

      <ul class="nav navbar-nav navbar-right">
          <li><a href="/tech/leaderboard"><span class="glyphicon glyphicon-log-in"></span> Leader Board</a></li>
        <li><a href="/tech/profile"><span class="glyphicon glyphicon-log-in"></span> Profile</a></li>
          <li><a href="/logout"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
      </ul>
    </div>
  </div>
</nav>
<div class="w3-card-4">
<div class="w3-panel w3-light-grey w3-border">
    <h1><p><img class="img-rounded" height="50" width="50" src={{ answer.pic.photo.url }}/>   {{ answer.answers }}</p></h1><br>
</div>
<div class="w3-container w3-theme w3-card-2">

<h2>Comments</h2>
</div>
    <ul class="list-group">
        {% for record1 in comment %}
        <li class="w3-theme-l3" style="position:relative"> <a class="list-group-item"><b><img class="img-rounded" height="20" width="20" src={{ record1.pic.photo.url }}/><font color="#dc143c">{{ record1.user.username }}</font> </b> {{ record1.comments }} </a></li>

        {% endfor %}
    </ul></div>
<br><h4>
<a class="btn btn-primary" href= '{% url 'create_comment_1' answer.id %}' role="button">Add new Answer</a>
</h4>
</body>
</html>

templates/comments_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load staticfiles %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <style>
        .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }

    /* Add a gray background color and some padding to the footer */
    footer {
      background-color: #f2f2f2;
      padding: 25px;
    }

    </style>
</head>
<body class="bg2">
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/tech/question">TechnicalForum</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">

      <ul class="nav navbar-nav navbar-right">
        <li><a href="/tech/profile"><span class="glyphicon glyphicon-log-in"></span> Profile</a></li>
          <li><a href="/logout"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
      </ul>
    </div>
  </div>
</nav>
<br><br><center>
<form class="form-horizontal" method="post">{% csrf_token %}
    <fieldset>
        <legend>{{ title }}</legend>
        {% for field in form %}<h2>
            {% if field.errors %}
                <div class="control-group error">
                    <label class="control-label">{{ field.label }}</label>
                    <div class="controls">{{ field }}
                        <span class="help-inline">
                            {% for error in  field.errors %}{{ error }}{% endfor %}
                        </span>
                    </div>
                </div>
            {% else %}
                <div class="control-group">
                    <label class="control-label">{{ field.label }}</label>
                    <div class="controls">{{ field }}
                        {% if field.help_text %}
                            <p class="help-inline"><small>{{ field.help_text }}</small></p>
                        {% endif %}
                    </div>
                </div>
            {% endif %}<br></h2>
        {% endfor %}
    </fieldset>
    <div class="form-actions">
        <button type="submit" class="btn btn-primary" >Submit</button>
    </div>
</form>
</center>
</body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Title</title>
    <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
<link r
      el="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Lato", sans-serif}
.w3-navbar,h1,button {font-family: "Montserrat", sans-serif}
.fa-anchor,.fa-coffee {font-size:200px}
      #container
      {
        position: relative;
      }

      #left-column
      {
          position: absolute;
          right: 800px;
      }

      #right-column
      {
        position: absolute;
        top: 0px;
        right: 300px;

      }
</style>

</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">TechnicalForum</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">

      <ul class="nav navbar-nav navbar-right">
        <li><a href="/login"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
          <li><a href="/tech/register"><span class="glyphicon glyphicon-log-in"></span> Register</a></li>
      </ul>
    </div>
  </div>
</nav>

<div class="w3-container w3-red w3-center w3-padding-128">
  <h1 class="w3-margin w3-jumbo">Technical Forum</h1>
  <p class="w3-xlarge">learn and thrive</p>
  <button class="w3-btn w3-padding-16 w3-large w3-margin-top">Get Started</button>
</div>
    <div id="container"><div id="left-column">
<h3 ><font color="#dc143c"> New User?? Please Register</font></h3>
        <center>
<h2><a class="btn btn-info" role="button" href={% url 'tech.views.adduser'%}>register</a></h2></div><br>
</center><br><br>
    <div id="right-column">
<h3><font color="#dc143c">Existing User?? Please Login</font></h3>
<h2><center><a class="btn btn-info" role="button" href="/login" >login</a></h2></div></div>
    </center><br><br><br>
</body>
</html>

templates/leader.html
<!DOCTYPE html>
<html lang="en">
<head>
        <meta charset="UTF-8">
    <title>List</title>
        {% load staticfiles %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
<link rel="stylesheet" href="/lib/w3-theme-blue.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<style>
        .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }

    /* Add a gray background color and some padding to the footer */
    footer {
      background-color: #f2f2f2;
      padding: 25px;
    }

    </style>
</head>
<body class="bg2">
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/tech/question">TechnicalForum</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">

      <ul class="nav navbar-nav navbar-right">
        <li><a href="/tech/profile"><span class="glyphicon glyphicon-log-in"></span> Profile</a></li>
          <li><a href="/logout"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
      </ul>
    </div>
  </div>
</nav>
<div class="w3-card-4">
<div class="w3-container w3-theme w3-card-2">
<h1>LeaderBoard</h1>
</div>
    <ul class="list-group">
        {% for record1 in list %}
        <li class="w3-theme-l3" style="position:relative"> <a class="list-group-item"href="{% url 'tech.views.profile1' record1.user_id_id %}"><b> <img class="img-rounded" height="20" width="20" src={{ record1.photo.url }}/><font color="#dc143c"> {{ record1.user_id.username }}</font></b> :::: <span class="w3-badge">{{ record1.credits }}</span> </a></li>
        {% endfor %}
    </ul>
<br>
</body>
</html>

templates/profile.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load staticfiles %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <style>
        .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }

    /* Add a gray background color and some padding to the footer */
    footer {
      background-color: #f2f2f2;
      padding: 25px;
    }

    </style>
</head>
<body bgcolor="#ff7f50">
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/tech/question">TechnicalForum</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">

      <ul class="nav navbar-nav navbar-right">
          <li><a href="/tech/leaderboard"><span class="glyphicon glyphicon-log-in"></span> Leader Board</a></li>
        <li><a href="/tech/profile"><span class="glyphicon glyphicon-log-in"></span> Profile</a></li>
          <li><a href="/logout"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
      </ul>
    </div>
  </div>
</nav>
<center><h1>Profile</h1></center><br>
<br>
<br>
<p>
    {% load staticfiles %}
<center><img class="img-circle" height="200" width="200" src={{ points.photo.url }}/>
<h4><a  href= "/tech/update/photo/{{ points.id }}">update profile photo</a></h4>
    <h1>{{ profile.username }}</h1><br>
<h2>Email:::{{ profile.email }}</h2>
<br>
<h2>Credits:::{{ points.credits }}</h2>

    <br>
</center>
    {% if questions %}
        <div class="w3-card-4">
<div class="w3-container w3-theme w3-card-2">
  <h1>My Questions</h1>
</div>

    <ul class="w3-ul w3-border-top">
        {% for record1 in questions %}
        <li class="w3-theme-l3" style="position:relative"> <a class="list-group-item" href="{% url 'tech.views.answers' record1.id %}"><b><img class="img-rounded" height="20" width="20" src={{ record1.pic.photo.url }}/> <font color="#dc143c">{{ record1.user.username }}</font></b> :::: {{ record1.questions }} </a></li>
        {% endfor %}
    </ul>
</div>

    {% endif %}

</body>
</html>

templates/profile_photo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load staticfiles %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <style>
        .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }

    /* Add a gray background color and some padding to the footer */
    footer {
      background-color: #f2f2f2;
      padding: 25px;
    }

    </style>
</head>
<body class="bg2">
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/tech/question">TechnicalForum</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">

      <ul class="nav navbar-nav navbar-right">
          <li><a href="/tech/leaderboard"><span class="glyphicon glyphicon-log-in"></span> Leader Board</a></li>
        <li><a href="/tech/profile"><span class="glyphicon glyphicon-log-in"></span> Profile</a></li>
          <li><a href="/logout"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
      </ul>
    </div>
  </div>
</nav>
<br><br><center>
<form class="form-horizontal" method="post" enctype="multipart/form-data">{% csrf_token %}
    <fieldset>
        <legend>{{ title }}</legend>
        {% for field in form %}<h2>
            {% if field.errors %}
                <div class="control-group error">
                    <label class="control-label">{{ field.label }}</label>
                    <div class="controls">{{ field }}
                        <span class="help-inline">
                            {% for error in  field.errors %}{{ error }}{% endfor %}
                        </span>
                    </div>
                </div>
            {% else %}
                <div class="control-group">
                    <label class="control-label">{{ field.label }}</label>
                    <div class="controls">{{ field }}
                        {% if field.help_text %}
                            <p class="help-inline"><small>{{ field.help_text }}</small></p>
                        {% endif %}
                    </div>
                </div>
            {% endif %}<br></h2>
        {% endfor %}
    </fieldset>
    <div class="form-actions">
        <button type="submit" class="btn btn-primary" >Submit</button>
    </div>
</form>
</center>
</body>
</html>

templates/questions_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object.questions }}"?</p>
    <input type="submit" value="Confirm" />
</form>
</body>
</html>

templates/questions_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>List</title>
        {% load staticfiles %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <style>

            .bg1 {
                background-color: lightskyblue;
}
        .bg2{
            background-color: thistle;
        }

    </style>

</head>
<body class="bg2">
<h1>Details</h1>
<ul>
    <li>{{ question.questions }}</li>
</ul>
<table>
    {% for i in question.answer_set.all %}
    <tr><td> {{ i.answers }} </td></tr>
    {% endfor %}
</table>
</body>
</html>